-- Phase 7: add missing acts profile columns (safe — all IF NOT EXISTS)
ALTER TABLE acts ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS home_city TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS home_state TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS facebook_url TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS instagram_url TEXT;
ALTER TABLE acts ADD COLUMN IF NOT EXISTS tiktok_url TEXT;
